[project]
name = "olmoearth-pretrain-minimal"
version = "0.0.8"
description = "Minimal package for loading and initializing OlmoEarth models"
authors = [
    { name = "OlmoEarth Team" },
]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.11"
dependencies = [
    "einops>=0.7.0",
    "huggingface_hub",
    "numpy>=1.26.4",
    "universal-pathlib>=0.2.5",
    "torch>=2.7",
]

[project.optional-dependencies]
dev = [
    "interrogate>=1.7.0",
    "pre-commit>=4.3.0",
    "pytest>=7.0.0",
    "ruff>=0.12.8",
    "olmoearth-pretrain==0.1.1",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["olmoearth_pretrain_minimal*"]

[tool.setuptools.package-data]
"olmoearth_pretrain_minimal.olmoearth_pretrain_v1.data.norm_configs" = ["*.json"]

[tool.ruff]
fix = true

[tool.ruff.lint]
extend-select = ["D", "I", "UP"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D"]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
testpaths = ["tests"]
